// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillBridge.Modules.Catalog.Infrastructure;

#nullable disable

namespace SkillBridge.Modules.Catalog.Infrastructure.Migrations;

[DbContext(typeof(CatalogDbContext))]
[Migration("20260923010014_Initial_Catalog")]
partial class Initial_Catalog
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("catalog")
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SkillBridge.BuildingBlocks.Events.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("content");

                b.Property<string>("Error")
                    .HasColumnType("text")
                    .HasColumnName("error");

                b.Property<DateTimeOffset>("OccurredOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occurred_on_utc");

                b.Property<DateTimeOffset?>("ProcessedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("processed_on_utc");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("type");

                b.HasKey("Id");

                b.HasIndex("OccurredOnUtc")
                    .HasFilter("processed_on_utc IS NULL");

                b.ToTable("outbox_messages", "catalog");
            });

        modelBuilder.Entity("SkillBridge.Modules.Catalog.Domain.Category", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<DateTimeOffset?>("DeletedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("deleted_at_utc");

                b.Property<string>("Description")
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)")
                    .HasColumnName("description");

                b.Property<string>("IconUrl")
                    .HasMaxLength(2048)
                    .HasColumnType("character varying(2048)")
                    .HasColumnName("icon_url");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean")
                    .HasColumnName("is_active");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean")
                    .HasColumnName("is_deleted");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("name");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_id");

                b.Property<string>("Slug")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("slug");

                b.Property<int>("SortOrder")
                    .HasColumnType("integer")
                    .HasColumnName("display_order");

                b.HasKey("Id");

                b.HasIndex("ParentId");

                b.HasIndex("Slug")
                    .IsUnique();

                b.ToTable("categories", "catalog", t =>
                    {
                        t.HasCheckConstraint("CK_categories_display_order", "display_order >= 0");

                        t.HasCheckConstraint("CK_categories_parent", "parent_id IS NULL OR parent_id <> id");
                    });
            });

        modelBuilder.Entity("SkillBridge.Modules.Catalog.Domain.Skill", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("CategoryId")
                    .HasColumnType("uuid")
                    .HasColumnName("category_id");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<string>("Description")
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)")
                    .HasColumnName("description");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean")
                    .HasColumnName("is_active");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("name");

                b.Property<string>("Slug")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("slug");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.HasIndex("Slug")
                    .IsUnique();

                b.ToTable("skills", "catalog");
            });

        modelBuilder.Entity("SkillBridge.Modules.Catalog.Domain.Tag", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("name");

                b.Property<string>("Slug")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("slug");

                b.HasKey("Id");

                b.HasIndex("Slug")
                    .IsUnique();

                b.ToTable("tags", "catalog");
            });

        modelBuilder.Entity("skill_tags", b =>
            {
                b.Property<Guid>("SkillId")
                    .HasColumnType("uuid")
                    .HasColumnName("skill_id");

                b.Property<Guid>("TagId")
                    .HasColumnType("uuid")
                    .HasColumnName("tag_id");

                b.HasKey("SkillId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("skill_tags", "catalog");
            });

        modelBuilder.Entity("SkillBridge.Modules.Catalog.Domain.Category", b =>
            {
                b.HasOne("SkillBridge.Modules.Catalog.Domain.Category", null)
                    .WithMany()
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("SkillBridge.Modules.Catalog.Domain.Skill", b =>
            {
                b.HasOne("SkillBridge.Modules.Catalog.Domain.Category", null)
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("skill_tags", b =>
            {
                b.HasOne("SkillBridge.Modules.Catalog.Domain.Skill", null)
                    .WithMany()
                    .HasForeignKey("SkillId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SkillBridge.Modules.Catalog.Domain.Tag", null)
                    .WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
