// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillBridge.Modules.Identity.Infrastructure.Data;

#nullable disable

namespace SkillBridge.Modules.Identity.Infrastructure.Migrations;

[DbContext(typeof(IdentityDbContext))]
partial class IdentityDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("identity")
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SkillBridge.BuildingBlocks.Events.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<string>("Error")
                    .HasColumnType("text");

                b.Property<DateTimeOffset>("OccurredOnUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset?>("ProcessedOnUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");

                b.HasIndex("ProcessedOnUtc");

                b.ToTable("outbox_messages", "identity");
            });

        modelBuilder.Entity("SkillBridge.Modules.Identity.Domain.ExternalLogin", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Provider")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("ProviderDisplayName")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("ProviderKey")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.HasIndex("Provider", "ProviderKey")
                    .IsUnique();

                b.ToTable("external_logins", "identity");
            });

        modelBuilder.Entity("SkillBridge.Modules.Identity.Domain.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CreatedByIp")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<DateTimeOffset>("ExpiresAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ReplacedByToken")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTimeOffset?>("RevokedAtUtc")
                    .IsConcurrencyToken()
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("SecurityStamp")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("Token")
                    .IsUnique();

                b.HasIndex("UserId");

                b.ToTable("refresh_tokens", "identity");
            });

        modelBuilder.Entity("SkillBridge.Modules.Identity.Domain.Role", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Description")
                    .HasMaxLength(250)
                    .HasColumnType("character varying(250)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("NormalizedName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.HasIndex("NormalizedName")
                    .IsUnique();

                b.ToTable("roles", "identity");
            });

        modelBuilder.Entity("SkillBridge.Modules.Identity.Domain.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("AccessFailedCount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0);

                b.Property<string>("AvatarUrl")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<bool>("IsEmailConfirmed")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<bool>("IsPhoneConfirmed")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<bool>("LockoutEnabled")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<DateTimeOffset?>("LockoutEndUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("NormalizedEmail")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(30)
                    .HasColumnType("character varying(30)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("SecurityStamp")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<bool>("TwoFactorEnabled")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("NormalizedEmail")
                    .IsUnique();

                b.ToTable("users", "identity");
            });

        modelBuilder.Entity("SkillBridge.Modules.Identity.Domain.UserRole", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("user_roles", "identity");
            });

        modelBuilder.Entity("SkillBridge.Modules.Identity.Domain.ExternalLogin", b =>
            {
                b.HasOne("SkillBridge.Modules.Identity.Domain.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("SkillBridge.Modules.Identity.Domain.RefreshToken", b =>
            {
                b.HasOne("SkillBridge.Modules.Identity.Domain.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("SkillBridge.Modules.Identity.Domain.UserRole", b =>
            {
                b.HasOne("SkillBridge.Modules.Identity.Domain.Role", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SkillBridge.Modules.Identity.Domain.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
